site_name: REO amplifier
site_url: https://reo.biomedtech.space

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Downloads: downloads.md
  - User Guide: user-guide/index.md
  - Contact: contact.md
  # - Blog: blog/index.md

theme:
  name: material
  language: en
  features:
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    # - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
    - toc.follow
    - toc.integrate

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: blue
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: blue
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

copyright: >
  Copyright &copy; 2014 - 2025 Space Biomed Technologies –
  <a href="#__consent">Change cookie settings</a>

extra:
  # alternate:
  #   - name: English
  #     link: /en/ 
  #     lang: en
  #   - name: Hungarian
  #     link: /hu/
  #     lang: hu

  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/spacebiomedtech/
    - icon: fontawesome/brands/github
      link: https://github.com/space-bmt
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/spacebiomedtech/

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  # - blog
  - privacy
  - search
